version: '3.7'

services:
  configurator:
    image: ${IMAGE_NAME:-frappe/erpnext}:${VERSION:?No image version set}
    deploy:
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.hostname == ${HOST_NAME:-petrol-uat}
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    entrypoint: ["bash", "-c"]
    command:
      - >
        bench set-config -g db_host $$DB_HOST;
        bench set-config -gp db_port $$DB_PORT;
        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
        bench set-config -g redis_socketio "redis://$$REDIS_SOCKETIO";
        bench set-config -gp socketio_port $$SOCKETIO_PORT;
        bench set-config -g developer_mode 1;
        bench set-config -g server_script_enabled 1;
        bench set-config -g allow_cors "*";
    environment:
      DB_HOST: ${BENCH_NAME:-mariadb}-db_db
      DB_PORT: 3306
      REDIS_CACHE: redis-cache:6379
      REDIS_QUEUE: redis-queue:6379
      REDIS_SOCKETIO: redis-socketio:6379
      SOCKETIO_PORT: 9000

volumes:
  sites:
    external: true
    # set to name of the sites volume
    name: ${BENCH_NAME:-erpnext}_sites
